version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
    ports:
      - 5432:5432
  nats:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    hostname: nats-main
